#!/bin/sh -ex

DB_NAME=zurmo
DB_USER=zurmo
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
DOMAIN=www.example.com

SRC=/usr/local/src
WEBROOT=/var/www/zurmo

# unpack and set required permissions
mkdir -p $WEBROOT
unzip $SRC/zurmo-*.zip -d $(dirname $WEBROOT)
rm $SRC/zurmo-*.zip
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/app/assets
chown -R www-data:www-data $WEBROOT/app/protected/data
chown -R www-data:www-data $WEBROOT/app/protected/runtime
chown -R www-data:www-data $WEBROOT/app/protected/config

# tweak php settings
CONF=/etc/php5/apache2/php.ini
sed -i "s|^memory_limit.*|memory_limit = 128M|" $CONF
sed -i "s|^upload_max_filesize.*|upload_max_filesize = 20M|" $CONF
sed -i "s|^post_max_size.*|post_max_size = 20M|" $CONF

CONF=/etc/php5/cli/php.ini
sed -i "s|^memory_limit.*|memory_limit = 128M|" $CONF

# tweak mysql settings
CONF=/etc/mysql/my.cnf
sed -i "s|^thread_stack.*|thread_stack            = 4096K|" $CONF
sed -i "s|^max_allowed_packet.*|max_allowed_packet      = 20M|g" $CONF

cat >/etc/mysql/conf.d/zurmo.cnf<<EOF
[mysqld]
optimizer_search_depth=0
max_sp_recursion_depth=20
EOF

rm -f /etc/mysql/conf.d/force_utf8.cnf

# configure apache
a2dissite 000-default
a2ensite zurmo
a2enmod rewrite

# start services
/etc/init.d/mysql start
/etc/init.d/memcached start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME --default-character-set=utf8;
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# perform installation
CONFIG=$WEBROOT/app/protected/config

cp $CONFIG/debugDIST.php $CONFIG/debug.php
sed -i "s|^    \$debugOn.*|    \$debugOn = false;|" $CONFIG/debug.php
sed -i "s|^    \$minifyScripts.*|    \$minifyScripts = true;|" $CONFIG/debug.php
sed -i "s|^    \$forceNoFreeze.*|    \$forceNoFreeze = false;|" $CONFIG/debug.php
sed -i "s|^    \$performanceOn.*|    \$performanceOn = false;|" $CONFIG/debug.php

cd $WEBROOT/app/protected/commands
./zurmoc install localhost \
    $DB_NAME $DB_USER $DB_PASS 3306 \
    $ADMIN_PASS http://$DOMAIN app/index.php demodata

chmod 640 $CONFIG/debug.php
chmod 640 $CONFIG/perInstance.php
chown www-data:www-data $CONFIG/debug.php
chown www-data:www-data $CONFIG/perInstance.php

# change super to admin
$MYSQL_BATCH --execute "UPDATE $DB_NAME._user SET username=\"jason\" WHERE username=\"admin\";"
$MYSQL_BATCH --execute "UPDATE $DB_NAME._user SET username=\"$ADMIN_NAME\" WHERE username=\"super\";"
$MYSQL_BATCH --execute "UPDATE $DB_NAME.person SET firstname=\"Admin\" WHERE firstname=\"Super\";"

# remove notifications generated during installation
$MYSQL_BATCH --execute "DELETE FROM $DB_NAME.notification WHERE type=\"RemoveApiTestEntryScriptFile\";"
$MYSQL_BATCH --execute "DELETE FROM $DB_NAME.notification WHERE type=\"HostInfoAndScriptUrlNotSetup\";"

# recommended for production use
rm -f $WEBROOT/app/test.php

# stop services
/etc/init.d/memcached stop
/etc/init.d/mysql stop

