#!/bin/bash -e
# regenerate zurmo mysql password

. /etc/default/inithooks

CONF=/var/www/zurmo/app/protected/config/perInstance.php
PASSWORD=$(mcookie)

sed -i "s|password.*|password         = '$PASSWORD';|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=zurmo --pass="$PASSWORD"

