#!/bin/bash -e
# set zurmo admin password and domain to serve

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/zurmo.py --pass="$APP_PASS" --domain="$APP_DOMAIN"

